# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Cocoaheads SGK'
tagline:          'Thessaloniki meetup for all things Apple dev'
description:      'We meet every last Tuesday of the month and bring together developers for drinks and talks about anything Apple related.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Thanos Theodoridis'
  url:            https://twitter.com/attheodo

paginate:         5
